title: Mikhail Chrestkha # your name (or website title) here
logo: "/images/photo_circle.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  <center>
  <b>Data Science & Machine Learning Platforms</b>
  <br>
  <a href="https://www.linkedin.com/in/mchrestkha/">LinkedIn</a>
  <a> | </a>
  <a href="https://twitter.com/mchrestkha">Twitter</a> 
  <a> | </a>
  <a href="https://github.com/mchrestkha">GitHub</a>   
   <a> | </a>
  <a href="https://medium.com/@mchrestkha">Medium</a> 
  <br><br>
  </center>
  <b>Certifications&#58;</b>
  <br>
  <a href="https://www.credential.net/5ada8707-778b-40b0-b41e-7262acb60b02">&#8901; TensorFlow Developer Certificate</a> 
  <br>
  <a href="https://www.credential.net/4520337d-a0ab-441f-81ba-5365d0fc3031">&#8901; Google Cloud Professional Machine Learning Engineer</a> 
  <br>
  <a href="https://www.credential.net/955c7441-6fbd-4ba0-bc19-f29010a9c788">&#8901; Google Cloud Professional Data Engineer</a> 
  <br><br>
  </center>
  <b>Top Posts&#58;</b>
  <br>
  <a href="https://www.linkedin.com/posts/mchrestkha_when-just-starting-to-deploy-ml-models-into-activity-6866626341421350912-jxcz?utm_source=linkedin_share&utm_medium=member_desktop_web">&#8901; When just starting to deploy ML models into production don’t over engineer your ML pipelines.</a> 
  <br>
  <a href="https://www.linkedin.com/posts/mchrestkha_whats-the-big-deal-about-serving-a-machine-activity-6912180719108710400-Vsk2?utm_source=linkedin_share&utm_medium=member_desktop_web">&#8901; What's the big deal about serving a machine learning model in production?</a> 
 
theme: jekyll-theme-minimal
google_analytics: UA-167468808-1 # your Google Analytics tracking ID here
