title: <center>Mikhail Chrestkha </center> # your name (or website title) here
logo: "/images/round_profile.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  Data Science & Machine Learning
  <br><br>
  Current focus areas include TensorFlow, XGBoost & SKLearn Solutions on Google Cloud
  <a href="https://www.linkedin.com/in/mchrestkha/">LinkedIn</a>
  <a> | </a>
  <a href="https://twitter.com/mchrestkha">Twitter</a> 
  <a> | </a>
  <a href="https://github.com/mchrestkha">GitHub</a>   
   <a> | </a>
  <a href="https://medium.com/@mchrestkha">Medium</a> 
  <br><br>
  Basketball, Running, Live Music 
 
theme: jekyll-theme-minimal
google_analytics: UA-167468808-1 # your Google Analytics tracking ID here
