title: <center>Mikhail Chrestkha </center> # your name (or website title) here
logo: "/images/round_profile.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  Data Science & Machine Learning
  <br><br>
  <a href="https://www.linkedin.com/in/mchrestkha/">LinkedIn</a>
  <a> | </a>
  <a href="https://twitter.com/mchrestkha">Twitter</a> 
  <a> | </a>
  <a href="https://github.com/mchrestkha">GitHub</a>   
   <a> | </a>
  <a href="https://medium.com/@mchrestkha">Medium</a> 
  <br><br>
  Current focus areas include Jupyter Notebook & MLOps solutions on Google Cloud 
  <br><br>
  Personal interests include basketball, running, & live music 
  <br><br>
  <ul>
  <li> <a href="https://www.credential.net/955c7441-6fbd-4ba0-bc19-f29010a9c788">Google Cloud Professional Data Engineer</a> </li>
  <li>Tea</li>
  <li>Milk</li>
  </ul>
 
theme: jekyll-theme-minimal
google_analytics: UA-167468808-1 # your Google Analytics tracking ID here
