title: Mikhail Chrestkha # your name (or website title) here
logo: "/images/round_profile.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  <center>
  <b>Data Science & Machine Learning Platforms</b>
  <br>
  <a href="https://www.linkedin.com/in/mchrestkha/">LinkedIn</a>
  <a> | </a>
  <a href="https://twitter.com/mchrestkha">Twitter</a> 
  <a> | </a>
  <a href="https://github.com/mchrestkha">GitHub</a>   
   <a> | </a>
  <a href="https://medium.com/@mchrestkha">Medium</a> 
  <br><br>
  </center>
  <b>Current Focus Areas&#58; </b><br>
  &#8901; AI Platform on Google Cloud  <br>
  &#8901; Jupyter Notebook Development Workflows  <br>
  &#8901; GPUs for Data & Machine Learning  <br>
  &#8901; Big Data Processing (BigQuery, Spark, Dask, Beam)  <br>
  <br>
  <b>Certifications&#58;</b>
  <br>
  <a href="https://www.credential.net/5ada8707-778b-40b0-b41e-7262acb60b02">&#8901; TensorFlow Developer Certificate</a> 
  <br>
  <a href="https://www.credential.net/955c7441-6fbd-4ba0-bc19-f29010a9c788">&#8901; Google Cloud Professional Data Engineer</a> 
 
theme: jekyll-theme-minimal
google_analytics: UA-167468808-1 # your Google Analytics tracking ID here
