title: Mikhail Chrestkha # your name (or website title) here
logo: "/images/photo_circle.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  <center>
  <b>Data Science & Machine Learning Platforms</b>
  <br>
  <a href="https://www.linkedin.com/in/mchrestkha/">LinkedIn</a>
  <a> | </a>
  <a href="https://twitter.com/mchrestkha">Twitter</a> 
  <a> | </a>
  <a href="https://github.com/mchrestkha">GitHub</a>   
   <a> | </a>
  <a href="https://medium.com/@mchrestkha">Medium</a> 
  <br><br>
  </center>
  <b>Current Focus Areas&#58; </b><br>
  &#8901; AI Platform on Google Cloud  <br>
  &#8901; Jupyter Notebook Development Workflows  <br>
  &#8901; GPUs for Data & Machine Learning  <br>
  &#8901; Big Data Processing (BigQuery, Spark, Dask, Beam)  <br>
  <br>
  <b>Certifications&#58;</b>
  <br>
  <a href="https://www.credential.net/5ada8707-778b-40b0-b41e-7262acb60b02">&#8901; TensorFlow Developer Certificate</a> 
   <br>
  <a href="https://www.credential.net/4520337d-a0ab-441f-81ba-5365d0fc3031">&#8901; Google Cloud Professional Machine Learning Engineer</a> 
  <br>
  <a href="https://www.credential.net/955c7441-6fbd-4ba0-bc19-f29010a9c788">&#8901; Google Cloud Professional Data Engineer</a> 
  
  
  It took 9 years into my career to start creating and sharing external content. Don't wait that long! Follow Rachel Thomas's great advice regarding ['Why you (yes, you) should blog'](https://medium.com/@racheltho/why-you-yes-you-should-blog-7d2544ac1045). Even 1 or 2 pieces of content a year adds up quickly throughout your career and can have a big impact on your writing & knowledge organization skills, meeting new people, and job/conference/meetup opportunities.  Here's another great post from Rachel on [how to write better blog posts and articles.](https://www.fast.ai/2019/05/13/blogging-advice/)
 
theme: jekyll-theme-minimal
google_analytics: UA-167468808-1 # your Google Analytics tracking ID here
