title: Mikhail Chrestkha # your name (or website title) here
logo: "/images/photo_circle.png?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  <center>
  <b>Data Science & Machine Learning Platforms</b>
  <br>
  <a href="https://www.linkedin.com/in/mchrestkha/">LinkedIn</a>
  <a> | </a>
  <a href="https://github.com/mchrestkha">GitHub</a>   
   <a> | </a>
  <a href="https://medium.com/@mchrestkha">Medium</a> 
  <br><br>
  </center> 
theme: jekyll-theme-minimal
google_analytics: UA-167468808-1 # your Google Analytics tracking ID here
